{{- if .Values.rbac.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.roles.name }}
  namespace: {{ .Release.Namespace }}
rules:
  {{- toYaml .Values.rbac.roles.rules | nindent 2 }}
{{- end }}