apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride | default "nginx" }}-svc
  {{- with .Values.service.labels }}
  labels:
    {{- toYaml . | nindent 4 }}-svc
  {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.portList }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | upper }}
  {{- end }}
  {{- with .Values.podLabels }}
  selectors:
    {{- toYaml . | nindent 4 }}
  {{- end }}
