nameOverride: ""

namespace: ""

sa:
  enable: true
  automount: true
  annotations: {}
  labels: {}

rbac:
  enable: true
  roles:
    name: ""
    rules:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list"]
  roleBinding:
    name: ""