nameOverride: ""

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []

replicaCount: 3

podAnnotations: {}
podLabels:
  app: nginx

sa:
  enable: true
  automount: true
  annotations: {}
  labels: {}

livenessProbe:
  httpGet:
    path: /
    port: 80
readinessProbe:
  httpGet:
    path: /
    port: 80

rbac:
  enable: true
  roles:
    name: ""
    rules:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list"]
  roleBinding:
    name: ""

service:
  type: ClusterIP
  labels: 
    svc: nginx
  portList:
    - port: 80
      protocol: tcp
      targetPort: 80
    - protocol: tcp 
      port: 443
      targetPort: 443
  annotations: {}
  selectors:
    app: nginx
  